name: CV application

on:      ##test on particular github branches
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:      ## permissions to read the contents
  contents: read

jobs:     
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]   ## operating versions to be tested on
        python-version: ["3.8"]

    steps:    
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}  ## setup python version
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}  ## check the specific python version
    - name: Install dependencies  ## to install all the required libraries
      run: |
        python -m pip install --upgrade pip  
        pip install flake8 pytest tox tox-gh-actions  
        pip install -r requirements.txt
    - name: Test with tox  
      run: tox

